### ISSUE TITLE
Bug: scenarios in the same feature create tests using different fixtures

### ISSUE THREAD

**Issue by wootra** [vitalets/playwright-bdd#52] opened 2023-09-05 14:51 UTC
**short description**
I am using classes extending one from others to share functionalities.
But as you guys know class can hold state as member variables.
even though I use the method that is inherited from the parent class, the state can be different.
in below test, even though I used the "Given" decorator to choose the child class, the result is just chosen based on where the specific decorator is located (parent class).
When the feature file is marked with specific fixture, it should consistently use the same fixture, but in below example, you will see the fixture for each tests are dynamically chosen based on the location of the each decorator. 
To fix this temporarily, I had to use a specific decorator that only belong to the fixture and it makes my BDD more verbose. 

**Given**

playright config
```
import { devices, defineConfig } from "@playwright/test";

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
import dotenv from "dotenv";
import { defineBddConfig } from "playwright-bdd";


dotenv.config({
	path: "./.env",
});
console.log("setting on env:"+ process.env.NODE_ENV);

dotenv.config({
	path: `./.env.${process.env.NODE_ENV}`,
});
dotenv.config({
	path: `./.env.${process.env.NODE_ENV}.local`,
});

console.log("public url is:", process.env.PUBLIC_URL);
const isUi = process.env.UI === 'true';
const testDir = defineBddConfig({
	paths: ["./features"],
	importTestFrom: './steps/fixtures.ts',
	require: ['./steps/*.ts'],
	quotes: 'backtick' // when fixture filles are converted to spec.ts files, quotes will be replaced to the backticks
});

// 
export default defineConfig({
	testDir,
	timeout: 60 * 1000,
	expect: {
		/**
		 * Maximum time expect() should wait for the condition to be met.
		 * For example in `await expect(locator).toHaveText();`
		 */
		timeout: 10000,
	},
	/* Run tests in files in parallel */
	fullyParallel: true,
	/* Fail the build on CI if you accidentally left test.only in the source code. */
	forbidOnly: !!process.env.CI,
	/* Retry on CI only */
	retries: process.env.CI ? 2 : 0,
	/* Opt out of parallel tests on CI. */
	workers: process.env.CI ? 1 : undefined,
	reporter: [["html", { outputFolder: "./reports" }]],
	use: {
	  	actionTimeout: 0,
		/* Base URL to use in actions like `await page.goto('/')`. */
		baseURL: process.env.PUBLIC_URL ?? 'http://my-dev.dimensional.com',
		screenshot: 'only-on-failure',
		/* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
		trace: "on-first-retry",
		testIdAttribute: "data-qa",
	},
	projects: [
		{
			name: "setup",
			testMatch: /\/__[a-zA-Z0-9].[a-zA-Z0-9_-]+\.feature\.spec\.js$/,
		},
		{
			name: "chromium",
			use: {
				...devices["Desktop Chrome"],
				// Use prepared auth state.
				storageState: ".auth/user.json",
			},
			testMatch: /\/[a-zA-Z0-9].[a-zA-Z0-9_-]+\.feature\.spec\.js$/,
			...(isUi? {}: {
				dependencies: ["setup"], // when UI mode, don't make dependency to save time.
			}),
		},
});

```
feature
```
@fixture:fundCenter
Feature: Some Feature
  Given: 
    Given I am on fund center  <=== choosing fund center. this whole feature should use fund center

  Scenario: Scenario 1
    Then I see "Some button" button
  Scenario: Scenario 2
    Then I see "Some tab" tab   <==== this decorator is in model center (parent class)
```

fixture
```
export
@Fixture<typeof test>("fundCenter")
class FundCenter extends ModelCenter{ // <==== extended from ModelCenter
        constructor(){
           super('fund');        
        }

        @Given("I am in fund center")
	async onFundCenter()
	{
		await this.openList('fund');
		this.modelStates.currentPage = "fund list";
	}	
       
        @Then("I see {string} button")
        async shouldSeeButton(button: string){
           ...
        }
}


export
@Fixture<typeof test>("modelCenter")
class ModelCenter {
     listType:string;
    constructor(listType: string = "model"){
       this.listType = listType; // by default, it is model, but it can be changed by child class
     }

    @Given("I am in model center")
	async onModelCenter()
	{
		await this.openList('fund');
		this.modelStates.currentPage = "fund list";
	}
        @Then("I see {string} tab")
        async shouldSeeTab(tab: string){
           ...
        }
}
```

fixtures.ts
```
type Pages = {
	modelCenter: ModelCenter;
	fundCenter: FundCenter;
};

export const test = base.extend<Pages>({
	modelCenter:async ({ page }, use) => use(new ModelCenter(page)),
	fundCenter:async ({ page }, use) => use(new FundCenter(page)),
});

```

**When**

```
npx bddgen
```
**Then**

It creates test using different fixtures
```
test.describe(`Some Feature`, () => {
  test.beforeEach(async ({ Given, fundCenter }) => {
    await Given(`I am on fundCenter`, null, { fundCenter });
  });
  test(`Scenario 1`, async ({ Then, fundCenter }) => {
    await Then(`I  see "some button" button`, null, { fundCenter });
  });

  test(`Scenario 2`, async ({ Then, modelCenter }) => {
    await Then(`I  see "some tab" tab`, null, { modelCenter }); // <== using modelCenter instead of fundCenter
  });

});
```
**Expected behavior**

for the same fixture, (especially when I explicitly defined `@fixture: fundCenter`), it should use the same fixture instead of using the class that holds original decorator.

**Isolated demo**

**Environment**

```
Playwright-bdd environment info:

platform: darwin
node: v16.14.2
playwright-bdd: v5.2.0
@playwright/test: v1.37.1
@cucumber/cucumber: v9.4.0
Playwright config file: playwright.config.ts
```

**Comment by vitalets** [comment] 2023-09-09 10:28
This is definitely bug, related to Background's own scope. I will investigate.
thanks @wootra

**Comment by vitalets** [comment] 2023-09-14 17:54
Fixed in `5.3.0`. Now file level `@fixture:xxx` should be considered in all scenarios of the file.
@wootra could you please re-check on your side?

**Comment by wootra** [comment] 2023-09-26 03:41
Sorry for late checking. I'll re-check tomorrow. Thank you for addressing it.

**Comment by wootra** [comment] 2023-09-27 13:38
I have tested, and got a worse situation. 
It is hard to describe but basically, the right class name is not showing.
<img width="501" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/97bf7cb4-8c60-48c5-969f-b9fb6f3a7100">
as you see modelCenter, it looks like the description belongs to modelCenter class, but it is not.
<img width="501" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/a905b16d-9a93-4876-8c23-3492cb5c296f">
it is supposed to comes from modelCompare. not because I added @fixture:modelCompare but because it belongs to ModelCompare class that is marked as modelCompare.
<img width="501" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/d4774799-5eda-4bde-ae43-3c02fcf463db">

as you see, my ModelCompare is extended from ModelCenter (marked as modelCenter).
this is my features file. I don't see any problem in here as well. 
<img width="539" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/da1a76c5-0e39-4d26-ac68-69d9f2c016db">

previously, at least the step description belongs to the class(feature), it could choose the right class. but not anymore.

**Comment by wootra** [comment] 2023-09-27 13:40
About the bug that is relative to this issue, it is showing the same issue.

this is one of the result file. as you see, beforeEach and other tests are using different fixture.
<img width="761" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/f427c6a9-1161-4fcb-9ae8-c7b7b89039e7">

**Comment by wootra** [comment] 2023-10-13 16:59
@vitalets I fixed what you mentioned.
One behavior that I mentioned before (using different fixture for the step description) is fixed:
<img width="737" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/7dcc51a1-9e41-4f53-814c-5648aef96e6b">
(now modelCompare is used for `I see compare models page`)

But still the feature.spec.js file is not using only modelCompare even though I set background for the modelCompare and set `@fixture: modelCompare`. 
<img width="560" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/7396efe9-1798-434f-8f77-242ba4fa32ac">

here is the extend states of my classes:
<img width="449" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/f248e655-75f6-4735-aa8e-fc59b68e18ae">

<img width="449" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/86f60db4-614d-441f-9f16-393daafe3bf0">

<img width="449" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/0349c8a0-d76d-40f3-aefb-5f59318521c5">

<img width="449" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/b0c5a067-0acc-4b53-9f9c-9b2c7cf2a4ba">

**Comment by vitalets** [comment] 2023-10-14 08:21
@wootra so the issue is that `modelCompare` is not used in `Open Build Modal in Model Center (Blank)` scenario. It uses `modelBuildModal` instead?

![image](https://github.com/vitalets/playwright-bdd/assets/1473072/22a0c3ef-32a9-4a04-b93d-e79c29c68128)

**Comment by vitalets** [comment] 2023-10-14 09:11
Tried to reproduce the behavior in https://github.com/vitalets/playwright-bdd-example/pull/4/files but works correctly.
Using similar class structure I've got the following generated test:
```js
test.describe(`feature`, () => {

  test.beforeEach(async ({ Given, modelCompare }) => {
    await Given(`step from modelCenter`, null, { modelCompare });
  });

  test(`Open Build Modal in Model Center (Blank)`, async ({ And, modelCompare }) => {
    await And(`step from modelBuildModal`, null, { modelCompare });
  });

});
```
Could you have a look on this to find what extra code in your case leads to incorrect structure?

**Comment by wootra** [comment] 2023-10-17 03:22
@vitalets I did not recognize the version is increased to 5.4.0 version. Let me try with the new version tomorrow. thanks!

**Closed** 2023-10-19 14:13 UTC
Labels: bug
