### ISSUE TITLE
Tests under subfolders of features folder are not executing for version greater than 4.0.0

### ISSUE THREAD

**Issue by magarwal19** [vitalets/playwright-bdd#44] opened 2023-08-04 08:14 UTC
Hi Team,
On the latest version when we run command "npx bddgen && npx playwright test"
then the .features-gen folder created do not create features folder and the command gets fail stating "Error: No tests found"
while if we downgrade to version 4.0.0, then features folder is created properly and able to execute tests

**Comment by vitalets** [comment] 2023-08-04 10:29
Hi @magarwal19 ! could you provide more details on your directory structure?

**Comment by magarwal19** [comment] 2023-08-07 05:54
@vitalets 
it is like below:
|- playwright
    |- features
        |- flow1
            |- feature1.feature
        |- flow2
            |- feature2.feature

**Comment by vitalets** [comment] 2023-08-08 05:59
I've got it. This caused by https://github.com/vitalets/playwright-bdd/issues/40 that simplifies output directory structure utilizing nearest common parent of feature files.
So now you will get:
```
.features-gen
  flow1
    feature1.feature.spec.js
  flow2
    feature2.feature.spec.js
```
instead of:
```
.features-gen
  features
    flow1
      feature1.feature.spec.js
    flow2
      feature2.feature.spec.js
```
Is it something that does not suit your project? I mean could you set outputDir to `.features-gen` in config - and it should work?

**Comment by magarwal19** [comment] 2023-08-08 11:38
I was not setting up output directory explicitly in playwright config file as i think it by defaults takes .features-gen

Problem with new version is that the run command
npx bddgen && npx playwright test

is failing stating no tests are found to run

**Comment by magarwal19** [comment] 2023-08-08 12:22
![Screenshot 2023-08-08 at 5 52 18 PM](https://github.com/vitalets/playwright-bdd/assets/47243226/b537b333-989d-4702-a375-7d8c258cd941)
![Screenshot 2023-08-08 at 5 52 30 PM](https://github.com/vitalets/playwright-bdd/assets/47243226/350d5cc8-bae4-45bd-97bd-5be79c08dc2e)

@vitalets  i tried adding outputDir, but still getting same error

**Comment by vitalets** [comment] 2023-08-08 17:08
> I was not setting up output directory explicitly in playwright config file as i think it by defaults takes .features-gen

You are right. I just wanted to double check your settings.
 
So I've tried to reproduce it in `playwright-bdd-exmple` [dir-structure-issue-44](https://github.com/vitalets/playwright-bdd-example/tree/dir-structure-issue-44) branch.

Having the same directory structure:
<img src="https://github.com/vitalets/playwright-bdd/assets/1473072/28f1d95a-7bf3-4698-8afe-3060ba37d300" width="50%"/>

And config:
```ts
const testDir = defineBddConfig({
  paths: ['features/**/*.{feature,feature.md}'],
  require: ['steps/*.ts'],
  importTestFrom: 'steps/fixtures.ts',
});
```
When run `npx bddgen && npx playwright test` all tests pass.

Could you clone `playwright-bdd-exmple` on that branch and run `npm test`?

**Comment by magarwal19** [comment] 2023-08-09 06:14
Hi @vitalets 
i checked out the repository and able to run tests with 
"npx bddgen && npx playwright test"  command

It seems i found the issue..
I was running a specific feature file in my local and there it fails saying no file is found.

I am able to replicate it with the repository you have shared..

Can you please try running below command:
**npx bddgen && npx playwright test features/flow1/homepage.feature**

**Comment by vitalets** [comment] 2023-08-10 12:24
> Can you please try running below command:
> **npx bddgen && npx playwright test features/flow1/homepage.feature**

Passing `.feature` files directly to Playwright CLI will not work, as Playwright expects js/ts files. But Playwright is smart enough to search for `**/*.spec.js` in provided argument. So you can just replace `features/...` with `.features-gen/...` to run a particular file:
```
npx bddgen && npx playwright test .features-gen/flow1/homepage.feature
```
or more accurately:
```
npx bddgen && npx playwright test .features-gen/flow1/homepage.feature.spec.js
```

**Comment by magarwal19** [comment] 2023-08-10 12:39
Hi @vitalets 

passing .feature file use to work earlier on old version.

with new changes if i change my run command to 

npx bddgen && npx playwright test flow1/homepage.feature

then this works...

But when we were using old way of giving complete paths "features/flow1...."
then it was easy as console helps to generate path by using tab keys..

**Comment by vitalets** [comment] 2023-08-11 07:43
I've got the point. Looking deeply on how Playwright handles passed arguments, I found that it converts them into [RegExp](https://github.com/microsoft/playwright/blob/b899d61a516f2a2018c4218d728a732e28611a38/packages/playwright-test/src/util.ts#L96) and applies to absolute file paths.
For example, when calling Playwright with `.feature` file:
```
npx bddgen && npx playwright test features/flow1/homepage.feature
```
It builds regexp like this:
```
/features\/flow1\/homepage.feature/gi
```
And applies it to all files from testDir (that is `.features-gen`):
```
.features-gen/features/flow1/homepage.feature.spec.js
...
```
When directory structure was the same as in `features`, regexp check was passing as generated files contain whole original filename. After #40 generated directory structure was simplified to the nearest parent dir and regexp check stopped passing.

Generally I like that "trick" with passing `.feature` files directly to Playwright. I think of introducing config option `outputDirStructure: 'preserve' | 'simplify'` to fit all needs. Preserving directory structure is also useful for screenshots storing, as they saved next to generated test files.

@magarwal19 thanks for bringing all this ideas :)

**Comment by magarwal19** [comment] 2023-08-11 07:58
That would really be helpful!
thank you for prompt response!

**Comment by vitalets** [comment] 2023-08-14 05:55
@magarwal19 while working on this fix I realized a workaround how we can pass `.feature` files to Playwright cli with current codebase. We could set `outputDir` to something ending with `features`, for example `outputDir: '.features'`:

```ts
const testDir = defineBddConfig({
  outputDir: '.features', // <- not .features-gen
  paths: ['features/**/*.{feature,feature.md}'],
  require: ['steps/*.ts'],
  importTestFrom: 'steps/fixtures.ts',
});
```
Then run command with `.feature` file:
```
npx bddgen && npx playwright test features/flow1/homepage.feature
```
Substring `features/flow1/homepage.feature` will match test file path `.features/flow1/homepage.feature.spec.js` and tests will run.

**Comment by vitalets** [comment] 2023-08-14 06:14
Concerning `outputDirStructure` I'm still thinking of approach. I should admit that output directory simplification introduced in #40 was not the best choice. Playwright heavily relies on directory structure for storing screenshots/snapshots, and we should try to keep it as stable as possible.

For example, the following features structure:
```
features
  flow1
    feature1.feature
```
produces the following output dir:
```
.features-gen
  feature1.feature.spec.js
  feature1.feature.spec.js-snapshots
    snapshot.png
```

Just adding a new feature file can cause full re-structure of outputDir that will invalidate all saved screenshots. It will be a headache for developers to find out why all screenshot tests are suddenly failed:
```
features
  flow1
    feature1.feature
  flow2
    feature2.feature
```
output dir:
```
.features-gen
  flow1
     feature1.feature.spec.js
  flow2
     feature2.feature.spec.js
  feature1.feature.spec.js-snapshots
    snapshot.png  // <-- screenshot is not valid as it's located not next to test file
```

**Comment by magarwal19** [comment] 2023-08-14 09:07
yes agree...
with current directory changes, when we open html report, then it does not show the screenshots in report as playwright not able to identify due to directory changes.

**Comment by vitalets** [comment] 2023-08-17 09:58
Fixed in 5.2.0. Introduced new config option [`featuresRoot`](https://vitalets.github.io/playwright-bdd/#/configuration?id=featuresroot) that solves this and other issues related to outputDir structure.

Unfortunately this is **possibly breaking** change for screenshot testing depending on project structure.
Added one more disclaimer in [changelog](https://github.com/vitalets/playwright-bdd/blob/main/CHANGELOG.md).

@magarwal19 could you check on your side with 5.2.0 that everything works correctly?

**Comment by magarwal19** [comment] 2023-08-17 10:24
Hi @vitalets 
tested it on new version 5.2.0
it is working as expected now and I am able to run specific test. Also screenshots and videos are properly mapped in default html and allure reports

**Comment by vitalets** [comment] 2023-08-17 12:22
Thank you!

**Closed by vitalets** 2023-08-17 12:22 UTC
