### ISSUE TITLE
Question: Generating cucumber reports with hooks

### ISSUE THREAD

**Issue by tcydik** [vitalets/playwright-bdd#107] opened 2024-03-14 07:09 UTC
I am trying to utilize cucumberReporter feature and I noticed that it is struggling to generate a report in case a test fails and contains "After" hooks.

My playwright config file:
  reporter: [
    ['list'],
    ['html', { open: 'never' }],
    ['junit', { outputFile: 'results.xml' }],
    cucumberReporter('html', {
      outputFile: 'cucumber-report/bdd_report.html',
    }),
  ],
and the hook it has problem with:
After({ tags: '@delete' }, async function ({ page, $testInfo }) {
  // Account cleanup
  const accountSettingsPage = createAccountSettingsPage(page, $testInfo)
  await accountSettingsPage.deleteAccount()
})

The message I get:
"Error in reporter Error: BDD data attachment is not found for test: As an user, I would like to create a basic account @smoke @regression @validation @test
Did you set enrichReporterData: true in the Playwright config?

    at TestCaseRun.getBddData (...\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\TestCaseRun.ts:71:13)
    at new TestCaseRun (...\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\TestCaseRun.ts:51:25)
    at ...\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\Builder.ts:122:27
    at Array.forEach (<anonymous>)
    at MessagesBuilder.createTestCaseRuns (...\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\Builder.ts:117:21)
    at MessagesBuilder.doBuildMessages (...\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\Builder.ts:73:10)"

Please note that this is not causing any issues if test case is passing although same hooks are applied.

Wanted to hear if this is a bug or I am settings up something wrong?

Thank you!

**Comment by vitalets** [comment] 2024-03-14 08:44
Sound like a bug. Could you create a reproducable example in https://github.com/vitalets/playwright-bdd-example

**Comment by tcydik** [comment] 2024-03-15 09:24
Thank you for quick reply. I will submit an example soon'ish

**Comment by tcydik** [comment] 2024-03-15 13:43
Seems like if I swap 

  getExecutedHooks(hookType: HookType) {
    return hookType === 'before'
      ? this.executedBeforeHooks.executedHooks
      : this.executedAfterHooks.executedHooks;
  }

With 
  getExecutedHooks(hookType: HookType) {
    return hookType === 'after'
      ? this.executedAfterHooks.executedHooks 
      : this.executedBeforeHooks.executedHooks;
  }
@..\node_modules\playwright-bdd\src\reporter\cucumber\messagesBuilder\TestCaseRun.ts

Then the problem disappears. Tried with having both hooks separately and together. Not sure why it makes a difference to be honest:)

**Comment by vitalets** [comment] 2024-03-15 16:56
Hmm.. In playwright-bdd error in hook should not block the report generation, it should show failing hook in the report. Something like this:
<img width="838" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/1473072/e10dd337-28c7-4727-9b16-219c236c53ab">

Reproducible demo would be helpful. Or could you just show the code of hook that causes this `BDD data attachment is not found...` error (if possible).

**Comment by tcydik** [comment] 2024-03-15 18:22
Scenario with tags from .feature file:
![image](https://github.com/vitalets/playwright-bdd/assets/79456598/ab74b04e-9257-410d-a293-1d10ce790308)
StepDefinition file:
![image](https://github.com/vitalets/playwright-bdd/assets/79456598/263714de-d06a-48b4-8cc3-76c090b9b64d)
Error output:
![image](https://github.com/vitalets/playwright-bdd/assets/79456598/fa6b4135-73e7-4a46-a700-87b08d11710f)
Playwright report output:
![image](https://github.com/vitalets/playwright-bdd/assets/79456598/33c7e56e-9682-4bb4-9d5b-55c6dc3cbd8f)


As you can see in this case I am simulating that the user could not enter the product and the code in the hook is based on deleting account within the product, which could not run and that is why hook failed. Hope this helps.

**Comment by vitalets** [comment] 2024-03-20 08:08
I've created the similar setup in https://github.com/vitalets/playwright-bdd-example/tree/failing-hook-107 
But can't reproduce the issue:
There is error in step and then error in after hook. Cucumber html report correctly shows both errors:
![image](https://github.com/vitalets/playwright-bdd/assets/1473072/cca841e3-e035-4035-95ef-adc19afc0365)

Playwright html report looks similar to yours:
![image](https://github.com/vitalets/playwright-bdd/assets/1473072/86343e11-cb3c-4891-9a67-13c1fda78dff)

Could you compare this example code with your setup and try to reproduce on it?

**Comment by tcydik** [comment] 2024-03-20 14:08
Hello, I tried this solution and it works for me as well. However when I add a sleep (i.e. 60000 msec) in the After hook, which is longer than Playwright configured timeout, which by default is 30000 msec, then I can reproduce it. So it something to do with timeout error.

**Comment by vitalets** [comment] 2024-03-21 08:21
Reproduced now, good catch! Checking for the fix.

**Comment by vitalets** [comment] 2024-03-23 16:22
Fixed in 6.0.3.
Please re-check on your side and reopen if there are any issues.

**Closed by vitalets** 2024-03-23 16:22 UTC
Labels: question, collecting feedback

**Comment by tcydik** [comment] 2024-03-25 08:59
Works fine now. Thanks!
