### ISSUE TITLE
Random test failures when running >40 tests in parallel

### ISSUE THREAD

**Issue by paolodg** [vitalets/playwright-bdd#31] opened 2023-07-06 12:40 UTC
I have a test suite with about 45 Scenarios, split across about 30 feature files. 
When I run them individually, all is good.
When I run less than 40, fully parallel, all is good
When I run more than 40, fully parallel, I experience random failures, always from the tests executed towards the end
If I shard them and run them in batches of 20 or 30, no failure happens

This is the error being thrown:

```
    TypeError: Cannot read properties of null (reading 'includes')

        at World.invokeStep (/Users/myName/workspace/myProject/node_modules/playwright-bdd/src/run/world.ts:53:41)
        at /Users/myName/workspace/myProject/starter-kit/async /Users/myName/workspace/myProject/starter-kit/tests/pwFeature/.feature-gen/tests/pwFeature/textInput.feature.spec.js:19:5
        at /Users/myName/workspace/myProject/starter-kit/async /Users/myName/workspace/myProject/node_modules/@playwright/test/lib/worker/workerMain.js:351:9
        at /Users/myName/workspace/myProject/starter-kit/async /Users/myName/workspace/myProject/node_modules/@playwright/test/lib/worker/workerMain.js:347:7
```

My configuration:
  OS: Mac OSx Ventura i7 32GB RAM
  playwright-bdd: 3.2.1
  @playwright/test: 1.33.0
  cucumber: 9.1.0
  chrome: 114
  nodejs: 16.16.0
  ts-node: 10.9.1

To write my step definitions, I am using cucumber style:

example:
```
Given('I am on the {string} page', async function(pageName: string) {
  const currentPage: PageInterface = globalThis[`${pageName}Page`];
  return currentPage.open();
});
```

To run my tests, I first run bddgen (there is nothing wrong with the generated spec files), then I use npx playwright test --config path/to/my/config

This is what my feature files look like:
```
Feature: Switch

  Background:
    Given create "switch" page

  Scenario: Switch displayed correctly
    Given I am on the "switch" page
    Then Switch is displayed correctly
    And Switch label is displayed correctly
```

They all include a background and are written in exactly the same way

**Comment by garrlker** [comment] 2023-07-06 18:02
I'm also seeing these. Haven't managed to create a reproduction to post here yet

**Comment by paolodg** [comment] 2023-07-07 08:00
According to the output, this should be the offending line:

`const res = **await getTestImpl(test)**._step(location, text, () => code.apply(this, parameters));`

**Comment by Jag46** [comment] 2023-07-07 08:05
Even I am facing similar flakiness issue while running test cases in parallel mode. But I am using Windows 10 machine. @paolodg Thanks for raising this.

**Comment by vitalets** [comment] 2023-07-07 08:25
Thanks for reporting. I'm investigating..
Two questions:
1. Could you try to run the same tests on the latest playwright 1.35?
2. Does the problem exist if you set `fullyParallel: false`?

**Comment by paolodg** [comment] 2023-07-07 08:55
Sorry @vitalets, forgot to mention this still happens when running tests NOT fully in parallel, i.e. fullyParallel: false

Will try to replicate with 1.35.0 and let you know

**Comment by paolodg** [comment] 2023-07-07 09:27
Unfortunately I can replicate with @playwright/test:1.35.0, using both fullyParallel:true and fullyParallel:false

My colleagues can replicate with 1.35.1

**Comment by vitalets** [comment] 2023-07-07 11:02
Trying to reproduce it using 50 files, currently can't catch.
1. Could you run the your tests with `workers: 1` in playwright config?
2. Could you generate and run tests using the data that I use:

sample.feature
```gherkin
Feature: Playwright site

    Background:
       Given I open url "https://playwright.dev"

    Scenario: Check title
        Given I open url "https://playwright.dev"
        When I click link "Get started"
        Then I see in title "Playwright"

    Scenario: Check title 2
        Given I open url "https://playwright.dev"
        When I click link "Get started"
        Then I see in title "Playwright"
```
Script to generate 50 files:
```js
/**
 * node temp.mjs
 */

import fs from 'fs';

const content = fs.readFileSync('features/sample.feature', 'utf8');
for (let i = 0; i < 50; i++) {
  fs.writeFileSync(`features/sample-${i}.feature`, content);
}
```

step definitions:
```ts
import { expect } from '@playwright/test';
import { Given, When, Then } from '@cucumber/cucumber';
import { World } from 'playwright-bdd';

Given('I open url {string}', async function (this: World, url: string) {
  await this.page.goto(url);
});

When('I click link {string}', async function (this: World, name: string) {
  await this.page.getByRole('link', { name }).click();
});

Then(
  'I see in title {string}',
  async function (this: World, keyword: string) {
    await expect(this.page).toHaveTitle(new RegExp(keyword));
  }
);
```

**Comment by paolodg** [comment] 2023-07-07 11:30
sure, I will try, but I am not passing the World object to my steps, so this setup looks a bit different from the one I have
First I'll try with your config, then I'll try to amend the one I currently have to use the world

**Comment by paolodg** [comment] 2023-07-07 11:36
This is my full config:
```

import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';

const readURLFromEnvVariable = function (): string {
  if (process.env.BASE_URL) {
    return process.env.BASE_URL;
  }
};

const testDir = defineBddConfig({
  paths: [
    './tests/pwFeature/accordion.feature',
    './tests/pwFeature/button.feature',
    './tests/pwFeature/checkbox.feature',
    './tests/pwFeature/checkboxGroup.feature',
    './tests/pwFeature/currencyField.feature',
    './tests/pwFeature/list.feature',
    './tests/pwFeature/confirmation.feature',
    './tests/pwFeature/dialog.feature',
    './tests/pwFeature/displayText.feature',
    './tests/pwFeature/dropdown.feature',
    './tests/pwFeature/genderField.feature',
    './tests/pwFeature/icon.feature',
    './tests/pwFeature/link.feature',
    './tests/pwFeature/list.feature',
    './tests/pwFeature/notification.feature',
    './tests/pwFeature/paragraph.feature',
    './tests/pwFeature/postcode.feature',
    './tests/pwFeature/spinner.feature',
    './tests/pwFeature/summaryBox.feature',
    './tests/pwFeature/tabs.feature',
    './tests/pwFeature/textInput.feature',
    './tests/pwFeature/textField.feature',
    './tests/pwFeature/tooltip.feature',
    './tests/pwFeature/errorSummary.feature',
    './tests/pwFeature/heading.feature',
    './tests/pwFeature/select.feature',
    './tests/pwFeature/switch.feature',
    './tests/pwFeature/table.feature',
    './tests/pwFeature/radioButtonGroup.feature',
    './tests/pwFeature/memorableDateField.feature',
    './tests/pwFeature/dateField.feature',
  ],
  require: ['./tests/step-definitions/examples/example_step_definitions.ts'],
  requireModule: ['ts-node/register'],
  outputDir: 'tests/pwFeature/.feature-gen',
});

export default defineConfig({
  timeout: 40000,
  testDir,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Number of workers as an absolute number or percentage of CPU */
  workers: 6,
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: readURLFromEnvVariable() || 'http://127.0.0.1:9001/',
    browserName: `chromium`,
    screenshot: 'only-on-failure',
    // video: 'retain-on-failure',
    actionTimeout: 10000,
    navigationTimeout: 10000,
    // trace: 'off',

    //Chrome Browser Config
    channel: `chrome`,
    // TODO: this param doesn't work with our current config
    // to run tests in headless mode, please prepend an env variable
    // in your script, e.g. HEADLESS=true yarn bdd:pw:examples
    // headless: false,

    launchOptions: {
      args: ['--disable-plugins', '--disable-extensions'],
      timeout: 20000,
    },
  },
  reporter: [
    // this shows a nice command line output, but it's not necessary to run tests
    ['list'],
    ['json', { outputFile: '../reports/output.json' }],
  ],

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'generated-tests',
      testDir: '../pwFeature/.feature-gen',
      use: { ...devices['Desktop Chrome'] },
    }
  ],
});

```

**Comment by paolodg** [comment] 2023-07-07 13:06
5 consecutive runs with workers:1, no failures

**Comment by vitalets** [comment] 2023-07-07 14:40
> 5 consecutive runs with workers:1, no failures

Ok, thanks. Looks like some race condition.
Btw, how do you setup your global context for this?
```
const currentPage: PageInterface = globalThis[`${pageName}Page`];
```

**Comment by paolodg** [comment] 2023-07-07 15:03
> > 5 consecutive runs with workers:1, no failures
> 
> Ok, thanks. Looks like some race condition. Btw, how do you setup your global context for this?
> 
> ```
> const currentPage: PageInterface = globalThis[`${pageName}Page`];
> ```

With the background: it creates a new page for each scenario, then it sets a global value for the page

initBasePage(page: Page): void {
     globalThis.page = page;
  }

**Comment by paolodg** [comment] 2023-07-10 09:13
@vitalets due to another piece of work unrelated to this, we upgraded to node 18.16.1 and CANNOT REPRODUCE ANYMORE

Statistic is consistent, got three different machine configurations working 100% of the time (about 20 runs per machine), will continue collecting statistics across different machine, but I would need you to confirm this is the issue

Could you please:
1. confirm your node version
2. try to downgrade to node 16.18.X and run tests again to see if we can replicate

Hopefully we are at the end of tunnel! :-)

**Comment by paolodg** [comment] 2023-07-10 09:45
> I'm also seeing these. Haven't managed to create a reproduction to post here yet

Could you please let us know what node version you are using?

**Comment by vitalets** [comment] 2023-07-10 10:36
> Could you please let us know what node version you are using?

I was testing on node v20.3.1

**Comment by vitalets** [comment] 2023-07-11 15:06
hi @paolodg thanks for the feedback!
I've also reproduced the issue on node v16.
Going deeper I found that the reason is in stacktrace capturing that is used for [detecting](https://github.com/vitalets/playwright-bdd/blob/fd986b3e5f8fca3df1c37d7dc328b8fbd7117e19/src/playwright/getLocationByStacktrace.ts#L17) step call locations.

Normally step call stacktrace is like following:
```
/playwright-bdd-example/node_modules/playwright-bdd/dist/playwright/getLocationByStacktrace.js 36
/playwright-bdd-example/node_modules/playwright-bdd/dist/run/world.js 27
/playwright-bdd-example/.features-gen/features/sample-27.feature.spec.js 17     <-- this frame (with depthIndex = 2) is used for step call reporting
/playwright-bdd-example/node_modules/@playwright/test/lib/worker/workerMain.js 345
...
```

But when running large number of files on **Node v16**  stacktrace sometimes gets microtasks injected and fileName = null:
```
/playwright-bdd-example/node_modules/playwright-bdd/dist/playwright/getLocationByStacktrace.js 36
/playwright-bdd-example/node_modules/playwright-bdd/dist/run/world.js 27
null null        <-- this actually causes "Cannot read properties of null (reading 'includes')"
node:internal/process/task_queues 61
node:internal/timers 437
/playwright-bdd-example/.features-gen/features/sample-27.feature.spec.js 17
/playwright-bdd-example/node_modules/@playwright/test/lib/worker/workerMain.js 345
...
```

And on **Node v18** microtask calls also appears (but no `null` filenames):
```
/playwright-bdd-example/node_modules/playwright-bdd/dist/playwright/getLocationByStacktrace.js 36
/playwright-bdd-example/node_modules/playwright-bdd/dist/run/world.js 27
node:internal/process/task_queues 61      <-- this frame will be incorrectly used for step call reporting
node:internal/timers 437
/playwright-bdd-example/.features-gen/features/sample-27.feature.spec.js 17
/playwright-bdd-example/node_modules/@playwright/test/lib/worker/workerMain.js 345
...
```
That means that even though it's passing on Node v18, step locations in report can be incorrect.

I'm going to do:
1. fix stacktrace handling so it will filter out `null`s and `node:` internal calls to find appropriate userland frame.
2. additionally check with raw Playwright if it has the same problem

**Comment by paolodg** [comment] 2023-07-11 15:44
perfect for me, please tag me in this issue when fixed, will upgrade when new version is available

**Comment by vitalets** [comment] 2023-07-11 17:37
Fixed in v3.3.0. Feel free to reopen if there are any issues.

@paolodg if possible, could you re-check on both node 16 and node 18 with all your test files?

**Closed by vitalets** 2023-07-11 17:37 UTC

**Comment by paolodg** [comment] 2023-07-14 08:54
will retest next week, hopefully monday

**Comment by paolodg** [comment] 2023-07-14 13:56
Fixed on both versions:
node 16.16.0
node 18.16.1

**Comment by vitalets** [comment] 2023-07-14 14:38
Thank you @paolodg
